#!/bin/bash




###########
#AUTHOR:Prasanthi
#DATE:01/05/2025
#
#Version:v1
#
#This Script report the AWS resource USAGE
###########
set -x

#aws s3
#aws ec2
#aws Lambda
#aws IAM


#List S3 buckets
echo "Print list of s3 buckets"
aws s3 ls >> resourceTracker

#List ec2 instances
echo "Print list of ec2 instances"
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId' >> resourceTracker



#List Lambda
echo "Print list of lambda functions"
aws lambda list-functions >> resourceTracker

#List IAM users
echo "Print list of IAM USERS"
aws iam list-users >> resourceTracker
